<?php

namespace AppBundle\Repository;

/**
 * IPWhitelistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IPWhitelistRepository extends \Doctrine\ORM\EntityRepository
{
}
