# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    atcore_database: default

services:
    # default configuration for services in *this* file
#    _defaults:
#        autowire: true
#        autoconfigure: true
#        public: false

    # makes classes in src/AppBundle available to be used as services
#    AppBundle\:
#        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
#        exclude: '../../src/AppBundle/{Entity,Repository}'

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    oracle.listener:
        class: Doctrine\DBAL\Event\Listeners\OracleSessionInit
        tags:
            - { name: doctrine.event_listener, event: postConnect, connection: atcore }

    app.avlabl_xml:
        class: AppBundle\Service\AvailabilityXml
        arguments: [%avlabl_directory%]

    app.atcore:
        class:  AppBundle\Service\Atcore
        arguments: [ "@doctrine.dbal.atcore_connection" ]

    app.geckoboard:
        class:  AppBundle\Service\GeckoBoard
        arguments: [ "@doctrine.dbal.atcore_connection" ]
